feature: more tab indicator options
akinsho/bufferline.nvim pull request #194
Opened 2021-08-22 07:12 UTC by ihasdapie

Add option & support for showing buffer name, tabnr, both, or provide a custom function for tab indicator text. 

![image](https://user-images.githubusercontent.com/54821716/130346042-cd7dc273-f641-4135-bce5-3d55934bb13e.png)

Not sure how this will impact offset/spacing calculation, etc. But some qualitative testing shows that it works well enough.

2021-08-22 08:56 UTC, akinsho requested changes
@ihasdapie thanks a lot for the PR 🙏🏿 🚀 it's much appreciated. I've made some comments about the implementation, I'm generally fine with the whole idea and only had a few things that I think could be tweaked. I get a lot of tabs plz issues that I've been considering how/if to accommodate, and this looks like a nice step.

2021-08-22 08:56 UTC, akinsho commented on README.md
> +    tab_indicator_option = 'both' | 'tabnr' | 'title' | function(str)
I think `tab_indicator_style` would be a better name for this rather than `option`

2021-08-22 08:56 UTC, akinsho commented on lua/bufferline/config.lua
> +      tab_indicator_option = 'both',
I don't think we should change the default behaviour. I think this new style will result in a bit of a duplication of buffer naming and take up space, so should be something someone opts into

2021-08-22 08:56 UTC, akinsho commented on lua/bufferline/tabs.lua
> +  local bufname = vim.fn.getbufinfo(
I don't think this should be done here. Information for a tab is derived in the `get` function rather than the render, which is just about the visual appearance of the derived data.

2021-08-22 08:56 UTC, akinsho commented on lua/bufferline/tabs.lua
> +  local bufname = vim.fn.getbufinfo(
You can add a key to the tab table in the `get` function called `name` and
do the name derivation there. I think you can also simplify this to
```lua
local buf = api.nvim_win_get_buf(tab.windows[1])
local name = fn.fnamemodify(api.nvim_buf_get_name(name), ':t')
````

2021-08-22 08:56 UTC, akinsho commented on lua/bufferline/tabs.lua
> +  if tab_indicator_style == 'tabnr' or (bufname == '' or not bufname) then
I don't think the name should default to just a number if the `bufname` is empty, I think only if the style is tabnr should there only be a number. You can default this to something like `[no name]`. Basically the `(bufname == '')` clause shouldn't be there, I think if using `both` or `title` and the bufname is `''` then it should be defaulted the same way as is done for buffers

2021-08-22 08:56 UTC, akinsho commented on lua/bufferline/tabs.lua
> +    bufname = bufname:match("^.+/(.+)$")
I think this is attempting to do the same thing as `fn.fnamemodify(name, ":t")` this is a more standard and battle tested way built into vim to handle shortening a filename. I've actually added it to the tab name derivation bit above so it doesn't have to be repeated twice here for both styles

2021-08-22 08:56 UTC, akinsho commented on lua/bufferline/tabs.lua
> +    bufname = tab.tabnr .. ': '  .. bufname:match("^.+/(.+)$")
I think this separator should be more easily customizable, as I can immediately see wanting to put a different symbol other than the colon there

2021-08-22 08:56 UTC, akinsho commented on lua/bufferline/tabs.lua
>    local length = strwidth(name) + strwidth(separator_component)
As your PR description alludes to, the `length` *has* to be incremented to accommodate these new changes since the name is what has changed, and it's length is being checked here this is why it is likely working. It'd be good to verify this if you can just log out the value locally to make sure it matches what you are expecting 🙏🏿

2021-08-22 08:58 UTC, akinsho commented on README.md
> +    tab_indicator_option = 'both' | 'tabnr' | 'title' | function(str)
Forgot to mention I think this should be advertised more prominently in the README and also updated in the help docs as well since hopefully it will reduce some "I want to see tabs" issues I get

2021-08-22 14:05 UTC, ihasdapie commented
@akinsho Your comments look great, I'll go make edits later today. I think `tab_ indicator_style` can be a table then?

One feature I was considering adding was custom tab names, so something that you can map to a keybinding that'll prompt the user for a tab name string. Thoughts?

2021-08-22 14:09 UTC, ihasdapie commented on lua/bufferline/tabs.lua
> +  local bufname = vim.fn.getbufinfo(
Yeah that looks better than what I had. This still has the problem of displaying the buffer name of the _first_ window in the tabpage, not the name of the _last active_ window which would probably be more desirable

2021-08-22 14:17 UTC, akinsho commented
@ihasdapie I don't think `tab_indicator_style` needs to be a table, it can just be  string enum of `'both' | 'tabnr' | 'title' | function` just the change of `option` to `style` since the config doesn't use the naming `option` for any other keys. `style` is the convention for changing the appearance of something I've used so far.

Regarding changing the name, I've seen some other plugins do this. It's a bummer it doesn't reference anything that actually exists in vim, so the name is fake/not related to anything in vim proper, but I guess the name could be added by the user and then stored in the tab object till they next reload vim. Later on if needed the names can be saved using uppercase `vim.g` variables because those are persisted across vim sessions.

2021-08-22 14:24 UTC, ihasdapie commented
@akinsho  Ah I was thinking of having it be a table because we wanted to customize the separator? Or just another option would be enough.

2021-08-22 14:55 UTC, akinsho commented
Ah I see, I think another option would be enough. Can't envision how the table work

2021-09-03 08:22 UTC, ihasdapie commented
No time this week or so, hopefully I can finish up the changes next week maybe

2022-03-08 22:57 UTC, closed without merging