Initial implementation of custom_filter in tabpages
akinsho/bufferline.nvim pull request #400
Opened 2022-04-29 08:03 UTC by GabMus

It's a bit hacky and I'm not too happy about the solution (calling the filter multiple times), but it accomplishes the goal.

A catch about this solution is that it basically ignores the filter if no buffer in the tab makes it through, not sure if this is desirable or not.

I'm opening this MR now to hopefully get some suggestions on how to improve it so that it can be merged.

Related to #398

2022-04-30 09:17 UTC, GabMus commented on lua/bufferline/tabpages.lua
> +  local buf = filter and filter(active_buf, buffers) and active_buf or buffers[1]
I realized this function doesn't work as intended if filter doesn't exist, so I fixed it in the last commit. Regardless, following is the logic behind the function change.

As it used to work before this MR, `get_tab_buffer_details` grabs the active buffer for the tab, meaning it doesn't care about filtering.

With this change, it still grabs the active buffer (hence the `active_buf` name), then it checks if it passes the filter. If it passes, then this function behaves as it used to. If it doesn't pass, then instead of using the active buffer for the tab, it uses the first buffer from `buffers`. `buffers` is passed to this function already filtered, meaning it's a list of buffers that already passed the filtering (or not, as in case no buffer passes the filtering the whole list of buffers is returned by `apply_buffer_filter`)

2022-05-08 10:34 UTC, GabMus commented
Any suggestions on what to improve to merge?

2022-05-08 11:01 UTC, akinsho requested changes
@GabMus I've left some comments, the biggest I'd like is to have filtering decoupled from fetching the tab buffers. That should just return all buffers free of filtering so filtering is a completely separate step, such that the filtering can be turned off by just commenting out a line or wrapping the section in an if else clause

2022-05-08 11:01 UTC, akinsho commented on lua/bufferline/tabpages.lua
> +    buf = filter(active_buf, buffers) and active_buf or buffers[1]
In order to do filtering separately, you might have to change this function to just take a buffer to show in the tab as a direct argument or something

2022-05-08 14:23 UTC, GabMus commented
I think it's much better now, please tell me if you think it still needs work.

2022-05-08 14:27 UTC, GabMus commented
Ok, fixed

2022-05-08 22:03 UTC, akinsho approved these changes
@GabMus this looks great now 👍🏾, thanks will merge this soon. Probs won't get a chance to test this properly, so if you're happy with it 👍🏾

2022-05-08 22:51 UTC, GabMus commented
Yeah, I'm using it on my machine and it seems to work just as I wanted. Feel free to merge any time, and thanks for your feedback!

2022-05-09 06:06 UTC, merged