Cterm color support
akinsho/bufferline.nvim pull request #415
Opened 2022-05-11 10:08 UTC by girishji

Please verify changes.

2022-05-11 11:17 UTC, akinsho requested changes
@girishji thanks for the PR. I will need to *thoroughly* test it because it *absolutely* must not break for other users not using `cterm`. One very important point is that I don't want to have choose between `get_cterm` color and `get_hex` in the future. This is too high a maintenance burden since I will have to now specifically reason about where to use it etc.

I think `get_hex` → `get_colour` and this should automatically return cterm values. Try to understand once this I is merged I will have to deal with this situation for maybe years, so I do not want to have to do a lot of if statements for cterm, because ultimately I will forget and probably not do it. Does this make sense

2022-05-11 11:17 UTC, akinsho commented on doc/bufferline.txt
> +When `termguicolors` is not enabled, user is expected to specify color values
```suggestion
When `termguicolors` is not enabled, a user is expected to specify color values
```

2022-05-11 11:17 UTC, akinsho commented on doc/bufferline.txt
> +            }
```suggestion
          }
```

2022-05-11 11:17 UTC, akinsho commented on doc/bufferline.txt
> +similar to the format above (use `ctermbg` and `ctermfg` instead). User can
```suggestion
similar to the format above (use `ctermbg` and `ctermfg` instead). A user can
```

2022-05-11 11:17 UTC, akinsho commented on lua/bufferline/ChangeLog
> +Author: Girish Palya <girishji@gmail.com>
This seems like an unrelated addition? Is this intentional? If I were to introduce a changelog, I'd expect it to be part of a separate PR and discussed separately

2022-05-11 11:17 UTC, akinsho commented on lua/bufferline/config.lua
> +          if not string.find(attribute, "cterm") then
Why is this change necessary, i.e. why does `cterm` require different error notification handling than hex here

2022-05-11 11:17 UTC, akinsho commented on lua/bufferline/ui.lua
> +  local ctermfg = colors.get_cterm_color({ name = bg_hls[state], attribute = "fg" })
Can the behaviour of `cterm` be internalised into `get_hex` and you just use a different flag e.g.
```lua
get_color({..., type = 'cterm'})
```
Or something. I don't like that the implementation details of thinking about cterm vs gui has leaked into the rest of the code base. It will mean that going forward I have to think about specifically getting cterm colors or not.

I think a necessary criteria of this plugin is that it does not complicate future development for me since if the maintenance burden is high this will not work for me.

2022-05-11 11:17 UTC, akinsho commented on lua/bufferline/ui.lua
> +  local ctermfg = colors.get_cterm_color({ name = bg_hls[state], attribute = "fg" })
Actually, maybe `get_color` should just always return the `cterm` value instead of special casing cterm with a separate function

2022-05-11 12:55 UTC, girishji commented on lua/bufferline/ChangeLog
> +Author: Girish Palya <girishji@gmail.com>
Not intentional. It appeared as a consequence of a script I use for checkin.

2022-05-11 12:59 UTC, girishji commented on lua/bufferline/config.lua
> +          if not string.find(attribute, "cterm") then
removed this check. i think i introduced it when i was playing with return value of -1 (didn't know about lua's nil). i was learning lua as i was playing with this.

2022-05-11 13:00 UTC, girishji commented on doc/bufferline.txt
> +When `termguicolors` is not enabled, user is expected to specify color values
agree

2022-05-11 13:00 UTC, girishji commented on doc/bufferline.txt
> +            }
agree

2022-05-11 13:00 UTC, girishji commented on doc/bufferline.txt
> +similar to the format above (use `ctermbg` and `ctermfg` instead). User can
agree

2022-05-11 13:04 UTC, girishji commented on lua/bufferline/ui.lua
> +  local ctermfg = colors.get_cterm_color({ name = bg_hls[state], attribute = "fg" })
you are using `name = hl` and not `bg_hls` for `guifg`. These things have different values that are not in end user's control. I would like to disassociate from this completely and have user specify it.

2022-05-11 13:19 UTC, girishji commented on lua/bufferline/ui.lua
> +  local ctermfg = colors.get_cterm_color({ name = bg_hls[state], attribute = "fg" })
It is better to separate `get_hex` from `get_color` and deal with extra cognitive overhead for now. Other option is to encapsulate both into one object which emits a hex `string` or color number `integer`. This way you can use it consistently everywhere, including in color_spec.

2022-05-11 13:45 UTC, girishji commented on lua/bufferline/ui.lua
> +  local ctermfg = colors.get_cterm_color({ name = bg_hls[state], attribute = "fg" })
you can review now, thx

2022-05-11 13:48 UTC, girishji commented
added changes. you can review, thx!

2022-05-11 13:54 UTC, akinsho commented
@girishji can you point this PR at `dev` instead of main so it can be tested thoroughly on that branch before going into `main`

2022-05-11 13:55 UTC, akinsho commented on ChangeLog
>  Author: Girish Palya <girishji@gmail.com>
This file is still present 😅

2022-05-11 13:58 UTC, akinsho commented on ChangeLog
>  Author: Girish Palya <girishji@gmail.com>
Ignore me I just saw the next commit

2022-05-11 14:18 UTC, akinsho requested changes
Added a few more small comments and one big one around the direction. I think that there shouldn't be two separate functions. I really do not want to have to deal with two different types of colour function. I think that cterm can just be an argument to get colour and the value return depend on that. I think you could create a wrapper type and type annotate it so it is clearer or you could return a `string | number`

2022-05-12 07:44 UTC, girishji commented
I will get to this today

2022-05-12 09:52 UTC, girishji commented on lua/bufferline/ui.lua
> -  highlights.set_one(new_hl, { guibg = guibg, guifg = guifg })
You have another parameter to `get_hex()` called `fallback`. How'd you account fo r that?

2022-05-12 13:02 UTC, closed without merging