feat(handle_click): remove vim script wrapper
akinsho/bufferline.nvim pull request #457
Opened 2022-06-19 14:24 UTC by nullchilly

Works for me :)

2022-06-19 14:53 UTC, akinsho requested changes
@nullchilly thanks for the PR left some comments about improving the naming to make the global variables less easy to accidentally override or discover. 

Also, you will need to update the tests probably you just need to change the names in the tests also

2022-06-19 14:53 UTC, akinsho commented on lua/bufferline/ui.lua
> +  component.attr.prefix = "%" .. id .. "@v:lua.nvim_bufferline_" .. func_name .. "@"
There are probably more places than just here probably where this needs to also be changed, please have a look to make sure you got them all

2022-06-19 14:53 UTC, akinsho commented on lua/bufferline/commands.lua
> +function _G.nvim_bufferline_handle_click(id, _, button)
This name is probably quite likely to cause a namespace clash. I suggest something much more secure if we are going to pollute the global namespace e.g. create a global table and then put a handle click function inside it e.g.

```lua
_G.___bufferline_private = _G.__bufferline_private or {} -- to guard against reloads
_G.___bufferline_private.handle_click = ...

```

2022-06-19 14:55 UTC, nullchilly commented on lua/bufferline/ui.lua
> +  component.attr.prefix = "%" .. id .. "@v:lua.nvim_bufferline_" .. func_name .. "@"
I searched them through telescope through the keyword `nvim_bufferline#` as that's the only way to call the vimscript I think?

2022-06-19 14:56 UTC, nullchilly commented on lua/bufferline/commands.lua
> +function _G.nvim_bufferline_handle_click(id, _, button)
Where do I put these global variables, at the top?

2022-06-19 14:59 UTC, akinsho commented on lua/bufferline/commands.lua
> +function _G.nvim_bufferline_handle_click(id, _, button)
@nullchilly you can put it near the top bufferline.lua file after the imports and maybe add a comment about why it's there

2022-06-19 15:12 UTC, akinsho commented on lua/bufferline.lua
> +-- the only way without autoload vimscript functions
```suggestion
-- @v:lua@ in the tabline only supports global functions, so this is
-- the only way to add click handlers without autoloaded vimscript functions
```

2022-06-19 15:14 UTC, akinsho commented on lua/bufferline.lua
> +_G.___bufferline_private = _G.__bufferline_private or {} -- to guard against reloads
```suggestion
_G.___bufferline_private = _G.___bufferline_private or {} -- to guard against reloads
```

2022-06-19 15:21 UTC, akinsho approved these changes
LGTM 👍🏿 thanks 🚀

2022-06-19 15:21 UTC, merged

2022-06-20 19:51 UTC, nullchilly commented
Since this is unmerged is it possible to reopen the pupl request?

2022-06-20 20:24 UTC, akinsho commented
@nullchilly I added the merge commit to the version 3 branch which i will merge when 0,8 is stable