feat: add option/ability to omit diagnostics entirely
akinsho/bufferline.nvim pull request #459
Opened 2022-06-20 14:10 UTC by vanarok

![2022-06-20T18:05:36,535511116+04:00](https://user-images.githubusercontent.com/6105977/174620332-bf634192-3a12-4372-a3e5-0ffb4b693f8b.png)
With the new diagnostics_pure=true option two things happen: 
1. The diagnostics count is hidden 
2. The spacing  after diagnostics is hidden.

2022-06-20 14:20 UTC, akinsho requested changes
@vanarok thanks for taking this on, I've recommended some changes because I think this can all be achieved without adding yet another config option. A user should simply specify `false` and there will be no diagnostics shown unless they pass in a function or nothing i.e. `nil`

2022-06-20 14:20 UTC, akinsho commented on lua/bufferline/ui.lua
> +  opts = opts or { when = true } and { pure = true }
This is an implementation detail of diagnostics that should not appear here at all, I would remove all of this

2022-06-20 14:20 UTC, akinsho commented on lua/bufferline/diagnostics.lua
> +  if config.options.diagnostics_pure then
I don't believe a new option is necessary @vanarok rather than doing this, I recommend changing this

https://github.com/akinsho/bufferline.nvim/blob/main/lua/bufferline/diagnostics.lua#L166-L170

To

```lua
  local indicator = ""
  if user_indicator and type(user_indicator) == "function" then
    local ctx = { buffer = element, tab = element }
    indicator = user_indicator(diagnostics.count, diagnostics.level, diagnostics.errors, ctx)
  elseif user_indicator == nil then -- If nothing is specified at all use the default
    indicator = " (" .. diagnostics.count .. ")"
  end
```

2022-06-20 14:20 UTC, akinsho commented on lua/bufferline/ui.lua
> +    spacing({ when = diagnostic, pure = config.options.diagnostics_pure }),
This can just be changed to 
```suggestion
    spacing({ when = diagnostic and diagnostic ~= "" }),
```

2022-06-20 15:20 UTC, akinsho commented
@vanarok please explain what filtering you are referring to? I don't really understand what you are filtering or how that relates to this PR

For context, I definitely do not want any new config option if possible there are already like 80 which is way too many. I also definitely do not want the implementation details of such a thing getting into the ui rendering layer in that way, so we need a solution that doesn't involve that (that is a blocker)

2022-06-20 15:24 UTC, akinsho commented
Ah, it seems maybe you mean that you are using the indicator to control what diagnostics appear in the bufferline, this is not how that was intended to be used to be honest. One solution is to allow the user indicator to return multiple values and use one to indicate emptiness, but tbh I don't really like the implicit usage of a function for creating and indicator as a filter function

2022-06-20 15:27 UTC, vanarok commented
> Ah, it seems maybe you mean that you are using the indicator to control what diagnostics appear in the bufferline, this is not how that was intended to be used to be honest. One solution is to allow the user indicator to return multiple values and use one to indicate emptiness, but tbh I don't really like the implicit usage of a function for creating and indicator as a filter function

`
                        diagnostics_pure = true,
                        diagnostics_indicator = function(count, level)
                            if level == 'error' then
                                return 'any text will be hidden with diagnostics_pure=true'
                            end
                        end,
`
That's what i mean.

2022-06-20 15:30 UTC, akinsho commented
@vanarok in the example above, it is unclear to me why a person would want to have no indicator but be returning text inside the diagnostic indicator but want it hidden?

2022-06-20 15:32 UTC, akinsho commented
Also, this is tangential since an option is a last resort to avoid anyway but the term `pure` is very vague, subject and not at all in keeping with the rest of the option naming. I would call it something much clearer and simpler like, `hide_diagnostic_indicator`

2022-06-20 15:57 UTC, akinsho commented
@vanarok I don't mind changing those if it allows us to avoid another option, but why return `true` from the indicator at all? Why use it at all instead of just setting `diagnostic_indicator = false`

2022-06-20 16:18 UTC, vanarok commented
And besides, the highlighting of the file name is also part of the diagnostic indicator. My original suggestion was to disable the count and diagnostic icons, the highlighting should not be disabled.

2022-06-20 16:42 UTC, akinsho commented
Ok I think we are going about this incorrectly because there's a sense of coupling the diagnostic indicator to stuff that isn't related to it. It is just a function to return a string of diagnostics, it isn't a mechanism for filtering. It also shouldn't affect the diagnostic highlights.

If it affects the diagnostic highlights e.g. removing the function removes the highlight, then that is a bug/problem to refactor. A user should be able to set false to the indicator and still get highlights for diagnostics for the buffer, since they should be unrelated.

The config example above I think shouldn't be a given because it represents a confusing set of options, e.g. a user is setting the value of a function called an indicator but setting another value to disable it. This is confusing and to be avoided, IMO.

I think a good starting place is to turn off the indicator, i.e. `false` and then see what the bugs or problems are with that approach. If the highlights aren't showing then that should be fixed since they shouldn't be connected.

If there are other issues feel free to raise them here if you don't know how to solve them but the ideal PR for this to my mind is the ability to explicitly disable the indicator and have your desired minimal aesthetic.

2022-06-26 12:32 UTC, akinsho commented
I've implemented what I mentioned here in #460, so I think this can be closed. You can now just set the indicator to false to achieve this, so there will be highlighting but no indicator

2022-06-26 12:32 UTC, closed without merging