Mark tabs as modified if any containing buffer is modified.
akinsho/bufferline.nvim pull request #554
Opened 2022-09-16 21:10 UTC by rwblokzijl

If a buffer is modified within a tab, the tab is only marked as modified if that buffer is in focus. This PR marks the tab as modified if any of the buffers in the tab are modified.

2022-09-17 10:17 UTC, akinsho commented on lua/bufferline/models.lua
> +  for _, buf in pairs(tab.buffers) do
Can this be factored out, I'd rather avoid logic being done inside this function directly and have it be more just set statements like `tab.modified = get_modified_state(buffers)`

2022-09-17 10:19 UTC, akinsho requested changes
This LGTM other than one comment I left. It's worth noting that whilst this seems fine to me, I can't predict whether some other tabs user will turn around and complain that they prefer the alternate way of working 🤷🏿‍♂️. Might call on you to defend this but definitely would rather only one mechanism here and this seems sensible

2022-09-17 15:52 UTC, rwblokzijl commented on lua/bufferline/models.lua
> +  for _, buf in pairs(tab.buffers) do
Yeah, I'll do that. Should i leave the function in the same file?

2022-09-17 16:42 UTC, akinsho commented on lua/bufferline/models.lua
> +  for _, buf in pairs(tab.buffers) do
Yes, it makes the most sense in that file. It's really just a very tiny stylistic preference. I just want to be able to look at that function and see each value being set directly somehow rather than following any logic around

2022-09-17 19:47 UTC, rwblokzijl commented
Sounds good. I cannot personally think of a workflow where this feature would be unwanted, but if one comes along I'll join the discussion.

2022-09-18 12:46 UTC, akinsho approved these changes
LGTM 🚀 thanks for tweaking it 👍🏿

2022-09-18 12:47 UTC, merged