refactor(tabs): tab diagnostics is the sum of child buffer diagnostics
akinsho/bufferline.nvim pull request #558
Opened 2022-09-18 14:37 UTC by rwblokzijl

In the same spirit as https://github.com/akinsho/bufferline.nvim/pull/554. This PR combines the diagnostic information shown on the line.

If the same file is open multiple times in the same tab, it is only included once.

2022-09-18 22:07 UTC, akinsho requested changes
@rwblokzijl thanks for the PR 🚀, left a few comments about tweaking some functions, using builtins where possible. Otherwise looks good 👍🏿

2022-09-18 22:07 UTC, akinsho commented on lua/bufferline/diagnostics.lua
> +local function get_severity_code(sev_name)
I think this can be simplified/changed to use `vim.tbl_add_reverse_lookup` so you could then delete this entire function and instead do
```lua
local severity_name = vim.tbl_add_reverse_lookup({
  [1] = "error",
  [2] = "warning",
  [3] = "info",
  [4] = "hint",
  [5] = "other",
}) -- this will add {error = 1, warning = 2, info = 3, ...}

-- Place where you need the code
severity_name[severity]
```

2022-09-18 22:14 UTC, rwblokzijl commented on lua/bufferline/tabpages.lua
> +local function contains_value(table, element)
I didn't know about `vim.tbl_contains` I'll change it :)

2022-09-19 08:45 UTC, akinsho commented on lua/bufferline/diagnostics.lua
> +function M.combine(diagnosticss)
@rwblokzijl it's more that the word `diagnosticss` is a typo in English. The word `diagnostic` is singular and `diagnostics` is plural. In your case you are adding two `ss` which is not correct.

2022-09-19 10:26 UTC, akinsho commented on lua/bufferline/diagnostics.lua
> +  for _, diagnostics_instance in pairs(diagnostics) do
This should just use the singluar here which is
```suggestion
  for _, diagnostic in pairs(diagnostics) do
```

2022-09-19 10:27 UTC, rwblokzijl commented on lua/bufferline/diagnostics.lua
> +  for _, diagnostics_instance in pairs(diagnostics) do
Yes, but that would reuse the variable name.

2022-09-19 10:28 UTC, akinsho commented on lua/bufferline/diagnostics.lua
> +  for _, diagnostics_instance in pairs(diagnostics) do
In which case something like `d` or `diag` is fine. I think it's fine to be terse here since it's to my mind pretty clear what each individual item is

2022-09-19 10:34 UTC, akinsho approved these changes
LGTM thanks for making the tweaks 👍🏿

2022-09-19 10:35 UTC, merged