[feat] Add `get_elements` command
akinsho/bufferline.nvim pull request #583
Opened 2022-10-09 19:19 UTC by andy-bell101

As discussed in #581 

I've included the path to the buffer in the output as well as I thought that would be useful. Otherwise it should be outputting what you were expecting.

There doesn't seem to be a wiki yet so I added the information to the README and vim docs.

2022-10-09 22:12 UTC, akinsho reviewed
This looks good @andy-bell101 I definitely prefer this approach, just made a small comment about using the map function and removing the command. Another thing would be ensuring that group indicators don't get included in the elements

2022-10-09 22:12 UTC, akinsho commented on lua/bufferline/commands.lua
> +    for _, e in ipairs(state.components) do
You can use `vim.tbl_map` i.e.

```lua
return vim.tbl_map(function(elem)
	return {...}
end, state.components)
```

2022-10-09 22:12 UTC, akinsho commented on lua/bufferline.lua
> +  cmd("BufferLineGetElements", function() M.get_elements() end, {})
I don't think a command is useful here since this functionality will need to be used in a function, this command essentially does nothing but also can't be used to do anything really

2022-10-10 11:52 UTC, andy-bell101 commented on lua/bufferline/commands.lua
> +    for _, e in ipairs(state.components) do
Done :)

2022-10-10 14:13 UTC, akinsho commented on README.md
> +#### Working with Elements
@andy-bell101 was just about to merge this when I noticed this explanation was in the README as well. I've actually moved everything other than just cursory videos and eye candy stuff into the help docs. The README now is basically just an annotated gallery so this bit should just be in the help docs alone

2022-10-10 14:14 UTC, akinsho requested changes
@andy-bell101 sorry didn't notice earlier that you'd added the explanation to the README but I actually don't put things like this in the README anymore just the help docs. I want the help docs to be where people go to figure out how the plugin works and the README is essentially an ad with shiny pictures 😆

2022-10-10 17:55 UTC, andy-bell101 commented
No worries should be gone now

2022-10-10 19:27 UTC, akinsho approved these changes
LGTM 👍🏿 thanks for your work on this

2022-10-10 19:32 UTC, merged

2022-10-10 20:12 UTC, andy-bell101 commented
No problem man, thanks for the plugins! Better sure I use a few of yours