Added `always_show_tab_close_icon` option
akinsho/bufferline.nvim pull request #646
Opened 2022-12-24 20:13 UTC by dwijesinghe

The tab close icon can look a little odd (and won't do anything) if there's only one tab in use. See [this reddit post ](https://www.reddit.com/r/neovim/comments/v9211b/can_we_remove_the_x_on_the_right_side_of_the/)

Since I would guess many people who use this plugin would be less inclined to use standard vim tabs - I thought it would make sense and improve aesthetics to remove it if there's only one tab in use (it will reappear if the user opens another tab). For those who want to always see the tab close icon, the `always_show_tab_close_icon` option can be set to `true` in setup (default is `false`). 

Please let me know your thought and btw I love this plugin :)

2023-01-02 15:24 UTC, akinsho commented
@dwijesinghe this is a good idea, thanks for the PR. I had been considering something similar, but hadn't gotten round to implementing it. The only suggestion I have would be to make this behaviour the default also I'd go as far as to remove the option tbh since frankly it's useless to have a button that does nothing and I get issues from users who are confused that the button "does not work" when there is only one tab open. I'd say just change this to be the only behaviour, i.e. only show the button if there is a tab.

2023-01-02 15:29 UTC, akinsho commented on doc/bufferline.txt
> +            always_show_tab_close_icon = true | false, -- if false the tab close icon will only appear if there is more than one tab
I'd say don't make this optional at all, I made a mistake by offering too many things as options. I'd say to just be decisive and make this the only behaviour since the alternative is useless

2023-01-02 15:30 UTC, akinsho requested changes
Made a couple of comments re. the implementation but definitely like this idea

2023-01-02 18:46 UTC, dwijesinghe commented
@akinsho Thanks! Just made those changes, its def a lot more succinct now. Let me know if there's anything else you want modified etc.

2023-01-03 14:06 UTC, akinsho approved these changes
LGTM

2023-01-03 14:07 UTC, merged