fix(get_icon): always use `get_icon` API of devicons
akinsho/bufferline.nvim pull request #653
Opened 2023-01-03 20:36 UTC by utilyre

This API has better icon matching. As an example, `package.json` would have a generic json icon before this commit, but now it gets the specific PackageJson icon and highlight.

Before:

![before](https://user-images.githubusercontent.com/91974155/210437247-e490a620-b04a-47f7-820b-926145bd617a.png)

After:

![after](https://user-images.githubusercontent.com/91974155/210437292-dbe12306-936a-4fe7-b1a8-877d370d79cb.png)

2023-01-03 22:16 UTC, akinsho commented
@utilyre this specific issue has come up before at least twice now. I only moved to using the filetype because a user using php kept getting the same icon even though hack and php have the same extension but different filetypes or something like that. Tbh I can't remember the specifics and I personally am not bothered by the issue he was, but this PR would essentially regress the behaviour for that user and cause issues all over again 😮‍💨.

Ultimately if there is no way to not break other people's use cases than I'd prefer this mechanism but a better no breaking solution would be preferred.

2023-01-04 10:05 UTC, utilyre commented
I see. I looked up `hack`, `hk`, and `php` in [web-devicons](https://github.com/nvim-tree/nvim-web-devicons) and there seems to be nothing related to a `hack` filetype.

So assuming that #549 was using the `override` option in `devicons.setup()`, his icon would be inside the `icons` table of [web-devicons](https://github.com/nvim-tree/nvim-web-devicons) and not the `filetypes` table (which is being used by `*_by_filetype` helpers).

Nonetheless, we can prevent breaking changes by a simple if statement for exceptionally using `get_icon_by_filetype` for a `php` extension, I suppose.

2023-01-04 19:34 UTC, utilyre commented
The last patch I applied covers the `hack` ft case.

2023-01-12 20:32 UTC, akinsho requested changes

2023-01-12 20:32 UTC, akinsho commented on lua/bufferline/utils/init.lua
> +  if opts.filetype == "hack" then return webdev_icons.get_icon_by_filetype(opts.filetype) end
@utilyre I would rather not hard code special cases like this into the code base at all. I'd rather break this for all special cases or provide users a way to handle this through some sort of official flexible mechanism

2023-01-23 21:16 UTC, camiloaromero23 commented
@utilyre @akinsho Just submitted a PR that addresses this issue from other point of view. I believe this is a better alternative that will not affect none of the users of the plugin and also will give the possibility to use the `get_icon` devicons API. [Get Icon Alternative PR](https://github.com/akinsho/bufferline.nvim/pull/669)

2023-01-24 17:09 UTC, closed without merging

2023-01-24 17:12 UTC, utilyre commented
Closed this in favor of #669