Feature: added slope separator
akinsho/bufferline.nvim pull request #659
Opened 2023-01-16 05:28 UTC by Taaqif

Should close #658

2023-02-15 10:39 UTC, akinsho commented on doc/bufferline.txt
> +* `padded_slope` - Same as `slope` but with extra padding which some terminals require.
@Taaqif do you know if this is actually needed or have you added it because you saw another style which used it. I'd rather not add this style as the original was a hack to fix the rendering of the slant in some terminals

2023-02-17 07:46 UTC, Taaqif commented on doc/bufferline.txt
> +* `padded_slope` - Same as `slope` but with extra padding which some terminals require.
Hi @akinsho 

Yeah I dont think this is really needed. I only added it as I copied the slant config. 
Happy to remove it as my tests showed the slope (without padding) works just fine on my terminal emulator 

Your call 👍 , I'll update the PR if you prefer

2023-02-17 08:23 UTC, akinsho commented on doc/bufferline.txt
> +* `padded_slope` - Same as `slope` but with extra padding which some terminals require.
@Taaqif yes please it might turn out to be necessary but I'd rather start with it not being there and wait to see if it ever comes up

2023-02-18 07:15 UTC, Taaqif commented on doc/bufferline.txt
> +* `padded_slope` - Same as `slope` but with extra padding which some terminals require.
All done!

Thanks for the guidance 😄

2023-02-18 09:29 UTC, akinsho requested changes
Woops looks like you've accidentally removed the existing padded variant

2023-02-18 09:29 UTC, akinsho commented on lua/bufferline/constants.lua
> -  padded_slant = "padded_slant",
@Taaqif you've removed more than just the one you've added, you've actually removed the `padded_slant` which is definitely needed

2023-02-18 09:29 UTC, akinsho commented on lua/bufferline/constants.lua
> -  [M.sep_names.padded_slant] = { "" .. M.padding, "" .. M.padding },
Please don't remove this option as it's actually needed, just the padded variant you added 🙏🏿

2023-02-19 03:23 UTC, Taaqif commented
> Woops looks like you've accidentally removed the existing padded variant

Oops @akinsho! 
Just re-added the padded_slant keys 🤕

2023-02-20 12:58 UTC, akinsho approved these changes
Tested this out locally and LGTM 👍🏿

2023-02-20 12:58 UTC, merged