Hotfix/fix bugs
akinsho/bufferline.nvim pull request #693
Opened 2023-02-21 20:20 UTC by otavioschwanck

Fixes https://github.com/akinsho/bufferline.nvim/issues/692 and https://github.com/akinsho/bufferline.nvim/issues/691

2023-02-21 21:27 UTC, akinsho requested changes
@otavioschwanck thanks for the PR. I mentioned in my review that I don't want details that are specific to the groups module being outside of that space since it causes the main module to depend on the implementation of `groups.lua` so I suggest creating a helper and exporting that, rather than exposing private state.

2023-02-21 21:27 UTC, akinsho commented on lua/bufferline/groups.lua
> +M.state = {
This state should not be exposed. Instead you should create a method that you can export from here and use in the `bufferline.lua` file e.g. 
```lua
function M.reset_manual_groupings()
	state.manual_groupings = {}
end

-- In bufferline.lua use
groups.reset_manual_grouping()
```

2023-02-21 21:27 UTC, akinsho commented on lua/bufferline.lua
> +    groups.state.manual_groupings = {}
Similarly the pinned key is only relevant to the groupings and should not be leaked outside that module because it shares unnecessary implementation details. You can add this line to helper function I suggested in `groups.lua`

2023-02-21 21:27 UTC, akinsho commented on lua/bufferline.lua
> +  cmd("BufferLineCyclePrev", function() M.cycle( -1) end, {})
Would be good to avoid unnecessary changes like this so this PR is easier to review

2023-02-21 21:27 UTC, akinsho commented on lua/bufferline/groups.lua
> +    persist_pinned_buffers()
A PR I made on `dev` recently removed this line and added it in elsewhere. Is this re-added intentionally?

2023-02-21 21:36 UTC, otavioschwanck commented on lua/bufferline/groups.lua
> +    persist_pinned_buffers()
Yes, it has to be in it to work properly.

2023-02-21 21:36 UTC, otavioschwanck commented on lua/bufferline.lua
> +  cmd("BufferLineCyclePrev", function() M.cycle( -1) end, {})
Just lua lint, sorry

2023-02-21 21:36 UTC, otavioschwanck commented on lua/bufferline.lua
> +    groups.state.manual_groupings = {}
Done

2023-02-21 21:36 UTC, otavioschwanck commented on lua/bufferline/groups.lua
> +M.state = {
Done

2023-02-21 22:21 UTC, akinsho requested changes
Getting there, just a couple more comments. Would really like to see the Pinned key not brought into the main bufferline module

2023-02-21 22:21 UTC, akinsho commented on lua/bufferline.lua
> +    vim.g[PINNED_KEY] = {}
It would also be good to not expose this here, can you move this into the `reset_manual_groups` function. We basically now have the `PINNED_KEY` maintained as a string in two places and they can fall out of sync

2023-02-21 22:21 UTC, akinsho commented on lua/bufferline.lua
> +  cmd("BufferLineCyclePrev", function() M.cycle( -1) end, {})
Can you revert these changes, since stylua will not like them and will try to fix it anyway

2023-02-22 01:36 UTC, otavioschwanck commented
Changes done!

2023-02-22 07:53 UTC, merged

2023-02-22 07:53 UTC, akinsho commented
LGTM 👍🏿 thanks