reset only for pinned
akinsho/bufferline.nvim pull request #696
Opened 2023-02-22 19:48 UTC by otavioschwanck

2023-02-22 20:04 UTC, akinsho requested changes
Thanks again for the PR. I've made some comments. Essentially I think this logic should moved entirely into the `groups.lua` function. I think that when deciding whether or not to reset manual groups *there* is where the check should happen

2023-02-22 20:04 UTC, akinsho commented on lua/bufferline/groups.lua
> +M.pinned_name = PINNED_NAME
Rather than exposing this, instead this logic should just be done inside of the `reset_manual_groupings`

2023-02-22 20:04 UTC, akinsho commented on lua/bufferline.lua
> +    if name == groups.pinned_name then
This logic should not be here, it breaks the encapsulation of that module. In general things should stay in the modules unless absolutely necessary for example now that the name is exposed `bufferline` in *general* now depends on the name, but that could be an implementation to change later so it shouldn't be exposed

2023-02-22 20:53 UTC, otavioschwanck commented on lua/bufferline.lua
> +    if name == groups.pinned_name then
Ok!

2023-02-22 21:42 UTC, otavioschwanck commented
Changes done!

2023-02-22 22:20 UTC, akinsho commented on lua/bufferline/groups.lua
> +    state.manual_groupings = {}
This shouldn't clear all groupings, I didn't realise what was happening sooner but a user can manually add a buffer to a group e.g.

```lua
local manual_groupings = {
  5 = "custom_docs_group",
  11 = "test_files",
  17 = "pinned",
  3 = "pinned"
}
```

the way your logic is written currently, then if I had added custom groups then this change would break my groups as well as clear the pinned ones.

Instead the logic should be
```lua
   if name == PINNED_NAME then
     vim.g[PINNED_KEY] = {}
   end
   for _, group_id in pairs(state.manual_groupings)
     if group_id == name then
		state.manual_groupings[group_id] = nil
     end
   end
```

This way this function can handle other types of groups without just clearing everything

2023-02-22 22:21 UTC, akinsho reviewed
@otavioschwanck now I look at it I think I didn't understand some of these changes.

So `manual_groupings` isn't only for `pinned` buffers it is a general state holder for any buffer to be assigned to a group by a user. A user can choose to manually add a buffer to a group so clearing all of it is actually not correct/causes bugs with the other functionality.

I've left an explanation of the change needed it's a small code change

2023-02-22 22:31 UTC, otavioschwanck commented on lua/bufferline/groups.lua
> +    state.manual_groupings = {}
> ```lua
>    if name == PINNED_NAME then
>      vim.g[PINNED_KEY] = {}
>    end
>    for _, group_id in pairs(state.manual_groupings)
>      if group_id == name then
> 		state.manual_groupings[group_id] = nil
>      end
>    end
> ```

done!

2023-02-22 22:34 UTC, akinsho commented on lua/bufferline/groups.lua
> +      state.manual_groupings[group_id] = nil
Sorry I didn't check the logic properly as it's been a long day you need to use the key which is the buffer number to delete the item

```lua
for buf, group_id ... do
	state.manual_groupings[buf] = nil
```

Please check the code carefully as well 🙏🏿

2023-02-23 01:39 UTC, otavioschwanck commented on lua/bufferline/groups.lua
> +      state.manual_groupings[group_id] = nil
oh shit, lucky you see it!

changes done!

2023-02-23 05:03 UTC, akinsho approved these changes
LGTM 👍🏿

2023-02-23 05:03 UTC, merged