Fix utils.is_list
akinsho/bufferline.nvim pull request #728
Opened 2023-04-14 18:13 UTC by bradsherman

https://github.com/akinsho/bufferline.nvim/pull/726 Introduced a bug because `utils.is_list` need to be executed in order to return a function that will return a boolean if the object is a list. This broke the tests, now it properly returns a `boolean`.

I ran the tests with the following command I got from the ci workflow yaml.
```sh
nvim --headless -u tests/minimal_init.lua -c "PlenaryBustedDirectory tests/ {minimal_init = 'tests/minimal_init.lua', sequential = true}"
```

I also ran the formatter with:
```sh
stylua --config-path=stylua.toml lua/
```

2023-04-14 18:27 UTC, bradsherman commented
@akinsho this should fix the problem introduced by the previous PR

2023-04-14 23:31 UTC, akinsho requested changes
Thanks for tracking down the bug and raising the PR @bradsherman I've just left a comment as I think this logic can be simplified greatly

2023-04-14 23:31 UTC, akinsho commented on lua/bufferline/utils/init.lua
> +local _is_list = mk_is_list()
I think this change can be inline i.e. and simplified i.e.

```lua
M.is_list = vim.tbl_isarray or vim.tbl_islist
```
I believe this line could replaace all of the other logic

2023-04-15 07:34 UTC, merged

2023-04-17 04:12 UTC, bradsherman commented
Sorry I was away from my computer this weekend. That's much nicer - thanks for taking it over the finish line!