Ignore disabled diagnostics
akinsho/bufferline.nvim pull request #816
Opened 2023-09-15 02:44 UTC by sidequestboy

2023-09-18 10:21 UTC, akinsho requested changes
@sidequestboy this looks good to me but the method you are using `is_disabled` was only added in nvim `v0.9.0` so if I merge this anyone on an older version of neovim will have issues. Can you add a check here to ensure that that method exists before using it, if not don't use it.

2023-09-19 08:51 UTC, akinsho commented on lua/bufferline/diagnostics.lua
> +    local is_new_nvim = fn.has("nvim-0.9") > 0
@sidequestboy I think this can be simplified and made more robust by just checking that the function exists. This is what I do elsewhere e.g.
if `vim.diagnostic.is_disabled ~= nil` rather than checking for the specific version. Also would be good to have a TODO comment for the future so I can come in and remove this eventually 🙏🏾

2023-09-19 18:12 UTC, sidequestboy commented
thanks for catching that, lmk if this looks good

2023-09-20 10:20 UTC, akinsho approved these changes
LGTM 👍🏾 thanks for tweaking this

2023-09-20 10:20 UTC, merged